### ISSUE TITLE
Import Error: cannot import name 'GenericStorage'

### ISSUE THREAD

**Issue by s77411** [oemof/oemof-examples#74]
Tried to use one of the both plotting example. Installed Oemof Version is 0.3.2 and oemof visio version is 0.0.1 on a windwos 10 computer. When executing both examples the error code: Import Error: cannot import name 'GenericStorage' gets returned. Fixed the bug by adding in the ...\oemof_visio\energy_system_graph.py in line 28 .components.
Old:
    from oemof.solph import GenericStorage 
New (Fixed):
    from oemof.solph.components import GenericStorage

**Comment by sharief091** [comment]
I tried the same for the plots and got the same error.
but as you mentioned: Fixed the bug by adding in the ...\oemof_visio\energy_system_graph.py in line 28 .components.
The lib is still old and not fixed. 
Could you help me out, please

**Comment by s77411** [comment]
Hey,
you just have to add in the code ...\oemof_visio\energy_system_graph.py in line 28: from oemof.solph import GenericStorage
to: from oemof.solph**.components** import GenericStorage and then it should work.

**Comment by sharief091** [comment]
Hi,
I have tried but I could not able to edit site-packages.
is there a way to add in the code ?

**Comment by sharief091** [comment]
I am using winpython environment. i have imported oemof_visio from github and am unable to do any changes. 
i think, it has to be edited in github. which i pulled a request. 

try: 
    from **oemof.solph import GenericStorage**
except ModuleNotFoundError:
    GenericStorage = None

**Comment by p-snft** [comment]
I guess, that's a problem with different versions of solph:
* `from oemof.solph import GenericStorage` works in solph v0.4 but not in v0.3 and (upcoming) v0.5
* `from oemof.solph.components import GenericStorage` works in all of these versions.

Thanks for https://github.com/oemof/oemof-visio/pull/8: As visio does not require a specific version, it should work with all of them.

PS: Is there a reason to use oemof v0.3 instead of oemof.solph v0.4?
